version: '3.7'
services:
  source:
    depends_on:
      - test-system
    build:
      context: ../../../common/syslog-source/
    volumes:
      - "../../../data/:/data/"
  test-system:
    build:
      context: test-system
      args: 
        TAG: ${LOGSTASH_VERSION:-latest}
