
[sources.syslog]
  type = "syslog"
  address = "0.0.0.0:9514" 
  mode = "tcp" 

[transforms.drop]
  type = "filter"
  inputs = [ "syslog" ]
  condition = 'false'

[sinks.blackhole]
  type = "blackhole"
  inputs   = ["drop"]
  print_amount = 1000000
