version: '3.7'
services:
  source:
    depends_on:
      - test-system
    build:
      context: ../../../common/hec-source/
  test-system:
    build:
      context: test-system
      args: 
        TAG: ${VECTOR_VERSION:-latest}
