
[sources.syslog]
  type = "syslog" # required
  address = "0.0.0.0:9514" # required, required when mode = "tcp" or mode = "udp"
  mode = "tcp" # required

[transforms.remap]
  # General
  type = "remap" # required
  inputs = ["syslog"] # required
  source = '''
  .procid,err = .procid + 420
  '''
[sinks.blackhole]
  type = "blackhole"
  inputs   = ["remap"]
  print_amount = 1000000
