
[sources.syslog]
  type = "syslog" # required
  address = "0.0.0.0:9514"
  mode = "tcp" 

[transforms.remap]
  type = "remap" 
  inputs = ["syslog"] 
  source = '''
  .procid,err = .procid + 420
  '''

[transforms.drop]
  type = "filter"
  inputs = [ "remap" ]
  condition = 'false'

[sinks.blackhole]
  type = "blackhole"
  inputs   = ["drop"]
  print_amount = 1000000

