version: '3.7'
services:
  source:
    depends_on:
      - test-system
    build:
      context: ../../../common/tcpjson-source/
  test-system:
    build:
      context: test-system
      args: 
        TAG: ${CRIBL_VERSION:-latest}
